packages:
  - apps/test-app
  - packages/cli-utils
  - packages/gyp-to-cmake
  - packages/cmake-rn
  - packages/ferric
  - packages/host
  - packages/node-addon-examples
  - packages/node-tests
  - packages/ferric-example

onlyBuiltDependencies:
  - esbuild
