import fs from "node:fs";
import path from "node:path";
import cp from "node:child_process";

import { type FunctionDecl, getNodeApiFunctions } from "weak-node-api";

export const CPP_SOURCE_PATH = path.join(import.meta.dirname, "../cpp");

/**
 * Generates source code which injects the Node API functions from the host.
 */
export function generateSource(functions: FunctionDecl[]) {
  return `
    // This file is generated by react-native-node-api
    // Versions.hpp must come first so <node_api.h> exposes the full v10 surface.
    #include <Versions.hpp>

    #include <dlfcn.h>
    #include <weak_node_api.hpp>

    #include <Logger.hpp>
    #include <RuntimeNodeApi.hpp>
    #include <RuntimeNodeApiAsync.hpp>

    #if defined(__APPLE__)
    #define WEAK_NODE_API_LIBRARY_NAME "@rpath/weak-node-api.framework/weak-node-api"
    #elif defined(__ANDROID__)
    #define WEAK_NODE_API_LIBRARY_NAME "libweak-node-api.so"
    #else
    #error "WEAK_NODE_API_LIBRARY_NAME cannot be defined for this platform"
    #endif

    namespace callstack::react_native_node_api {

    void injectIntoWeakNodeApi() {
    void *module = dlopen(WEAK_NODE_API_LIBRARY_NAME, RTLD_NOW | RTLD_LOCAL);
    if (nullptr == module) {
      log_debug("NapiHost: Failed to load weak-node-api: %s", dlerror());
      abort();
    }

    auto inject_weak_node_api_host = (InjectHostFunction)dlsym(
    module, "inject_weak_node_api_host");
    if (nullptr == inject_weak_node_api_host) {
      log_debug("NapiHost: Failed to find 'inject_weak_node_api_host' function: %s", dlerror());
      abort();
    }

    log_debug("Injecting NodeApiHost");
    inject_weak_node_api_host(NodeApiHost {
      ${functions.flatMap(({ name }) => `.${name} = ${name},`).join("\n")}
      });
    }
    } // namespace callstack::react_native_node_api
  `;
}

async function run() {
  const nodeApiFunctions = getNodeApiFunctions();

  const source = generateSource(nodeApiFunctions);
  const sourcePath = path.join(CPP_SOURCE_PATH, "WeakNodeApiInjector.cpp");
  await fs.promises.writeFile(sourcePath, source, "utf-8");
  cp.spawnSync("clang-format", ["-i", sourcePath], { stdio: "inherit" });
}

run().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
