[package]
name = "PROJECT_NAME"
version = "1.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies.napi]
version = "3.1"
default-features = false
# see https://nodejs.org/api/n-api.html#node-api-version-matrix
features = ["napi3"]

[dependencies.napi-derive]
version = "3.1"
features = ["type-def"]

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
opt-level = "z"
