/**
 * This file was generated by
 * ╭─────────────────────────╮
 * │░█▀▀░█▀▀░█▀▄░█▀▄░▀█▀░█▀▀░│
 * │░█▀▀░█▀▀░█▀▄░█▀▄░░█░░█░░░│
 * │░▀░░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀▀▀░│
 * ╰─────────────────────────╯
 * Powered by napi.rs
 */
/* eslint-disable */
export declare function sum(a: number, b: number): number
