/* eslint-disable */

/**
 * This file was generated by
 * ╭─────────────────────────╮
 * │░█▀▀░█▀▀░█▀▄░█▀▄░▀█▀░█▀▀░│
 * │░█▀▀░█▀▀░█▀▄░█▀▄░░█░░█░░░│
 * │░▀░░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀▀▀░│
 * ╰─────────────────────────╯
 * Powered by napi.rs
 */

module.exports = require('./ferric_example.node');
