import fs from "node:fs";
import path from "node:path";

import { DIRS, PACKAGE_DIR, findRootCMakeProjects } from "./cmake-projects.mjs";

// A single root project lets cmake-rn build every example in one invocation.
// It is generated rather than globbed, because a glob is evaluated once at
// configure time and would miss examples copied in afterwards.
const projectDirectories = DIRS.flatMap(findRootCMakeProjects)
  .map((directory) =>
    path.relative(PACKAGE_DIR, directory).split(path.sep).join(path.posix.sep),
  )
  .sort();

const outputPath = path.join(PACKAGE_DIR, "CMakeLists.txt");

fs.writeFileSync(
  outputPath,
  [
    "# Generated by scripts/generate-root-project.mts - do not edit.",
    "cmake_minimum_required(VERSION 3.15...3.31)",
    "project(node-addon-examples)",
    "",
    ...projectDirectories.map((directory) => `add_subdirectory(${directory})`),
    "",
  ].join("\n"),
  "utf-8",
);

console.log(
  `Generated ${path.relative(process.cwd(), outputPath)} with ${projectDirectories.length} sub-projects`,
);
