on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - run: npm ci
      - run: npm run lint
  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    name: Test (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        # Version here should match the one in React Native template and packages/cmake-rn/src/cli.ts
      - run: sdkmanager --install "ndk;27.1.12297006"
      - run: npm ci
      - run: npx nx run-many -t test
