name: Check visionOS

env:
  # Version here should match the one in React Native template and packages/cmake-rn/src/cli.ts
  NDK_VERSION: 27.1.12297006
  # Enabling the Gradle test on CI (disabled by default because it downloads a lot)
  ENABLE_GRADLE_TESTS: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-visionos:
    name: Test Ferric with visionOS Triplets
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: tools platform-tools ndk;${{ env.NDK_VERSION }}
      # Install visionOS targets for Rust
      - run: rustup target add aarch64-apple-visionos aarch64-apple-visionos-sim
      # Also install other required targets
      - run: rustup target add x86_64-linux-android aarch64-linux-android armv7-linux-androideabi i686-linux-android aarch64-apple-ios-sim
      - run: npm ci
      - run: npm run build
      # Bootstrap host package to get weak-node-api and ferric-example with visionOS support
      - run: npm run bootstrap --workspace react-native-node-api
      - run: npm run bootstrap --workspace @react-native-node-api/ferric-example
        env:
          CMAKE_RN_TRIPLETS: aarch64-apple-visionos,aarch64-apple-visionos-sim
          FERRIC_TARGETS: aarch64-apple-visionos,aarch64-apple-visionos-sim
      - run: npm run lint
        env:
          DEBUG: eslint:eslint