name: Check visionOS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-visionos:
    name: Test Ferric with visionOS Triplets
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      # Bootstrap Rust compiler with visionOS targets (tier 3)
      # visionOS targets are not available as prebuilt targets and need to be built from source
      - name: Clone Rust repository
        run: git clone https://github.com/rust-lang/rust.git rust-source
      - name: Configure Rust build for visionOS targets
        run: |
          cd rust-source
          cat > config.toml << 'EOF'
          [build]
          target = ["x86_64-apple-darwin", "aarch64-apple-visionos", "aarch64-apple-visionos-sim"]
          
          [target.aarch64-apple-visionos]
          cc = "clang"
          cxx = "clang++"
          
          [target.aarch64-apple-visionos-sim]
          cc = "clang"  
          cxx = "clang++"
          EOF
      - name: Bootstrap Rust with visionOS support
        run: |
          cd rust-source
          ./x.py build --target aarch64-apple-visionos,aarch64-apple-visionos-sim
        timeout-minutes: 120
      - name: Install bootstrapped Rust toolchain
        run: |
          cd rust-source
          ./x.py install --target aarch64-apple-visionos,aarch64-apple-visionos-sim
      # Also install required iOS targets for the bootstrap process
      - run: rustup target add aarch64-apple-ios-sim
      - run: npm ci
      - run: npm run build
      # Bootstrap host package to get weak-node-api and ferric-example with visionOS support
      - run: npm run bootstrap --workspace react-native-node-api
      - run: npm run bootstrap --workspace @react-native-node-api/ferric-example
        env:
          CMAKE_RN_TRIPLETS: aarch64-apple-visionos,aarch64-apple-visionos-sim
          FERRIC_TARGETS: aarch64-apple-visionos,aarch64-apple-visionos-sim